export const models = [
  { id: "aion-labs/aion-1.0", name: "Aion-1.0" },
  { id: "aion-labs/aion-1.0-mini", name: "Aion-1.0-Mini" },
  { id: "aion-labs/aion-rp-llama-3.1-8b", name: "Aion-RP 1.0 (8B)" },
  { id: "thedrummer/anubis-pro-105b-v1", name: "Anubis Pro 105B V1" },
  { id: "arcee-ai/arcee-blitz", name: "Arcee Blitz" },
  { id: "openrouter/auto", name: "Auto Router" },
  { id: "arcee-ai/caller-large", name: "Caller Large" },
  { id: "openai/chatgpt-4o-latest", name: "ChatGPT-4o" },
  { id: "anthropic/claude-3-haiku", name: "Claude 3 Haiku" },
  {
    id: "anthropic/claude-3-haiku:beta",
    name: "Claude 3 Haiku (self-moderated)",
  },
  { id: "anthropic/claude-3-opus", name: "Claude 3 Opus" },
  {
    id: "anthropic/claude-3-opus:beta",
    name: "Claude 3 Opus (self-moderated)",
  },
  { id: "anthropic/claude-3-sonnet", name: "Claude 3 Sonnet" },
  {
    id: "anthropic/claude-3-sonnet:beta",
    name: "Claude 3 Sonnet (self-moderated)",
  },
  { id: "anthropic/claude-3.5-haiku", name: "Claude 3.5 Haiku" },
  {
    id: "anthropic/claude-3.5-haiku-20241022",
    name: "Claude 3.5 Haiku (2024-10-22)",
  },
  {
    id: "anthropic/claude-3.5-haiku-20241022:beta",
    name: "Claude 3.5 Haiku (2024-10-22) (self-moderated)",
  },
  {
    id: "anthropic/claude-3.5-haiku:beta",
    name: "Claude 3.5 Haiku (self-moderated)",
  },
  { id: "anthropic/claude-3.5-sonnet", name: "Claude 3.5 Sonnet" },
  {
    id: "anthropic/claude-3.5-sonnet-20240620",
    name: "Claude 3.5 Sonnet (2024-06-20)",
  },
  {
    id: "anthropic/claude-3.5-sonnet-20240620:beta",
    name: "Claude 3.5 Sonnet (2024-06-20) (self-moderated)",
  },
  {
    id: "anthropic/claude-3.5-sonnet:beta",
    name: "Claude 3.5 Sonnet (self-moderated)",
  },
  { id: "anthropic/claude-3.7-sonnet", name: "Claude 3.7 Sonnet" },
  {
    id: "anthropic/claude-3.7-sonnet:beta",
    name: "Claude 3.7 Sonnet (self-moderated)",
  },
  {
    id: "anthropic/claude-3.7-sonnet:thinking",
    name: "Claude 3.7 Sonnet (thinking)",
  },
  { id: "anthropic/claude-opus-4", name: "Claude Opus 4" },
  { id: "anthropic/claude-sonnet-4", name: "Claude Sonnet 4" },
  { id: "anthropic/claude-2", name: "Claude v2" },
  { id: "anthropic/claude-2:beta", name: "Claude v2 (self-moderated)" },
  { id: "anthropic/claude-2.0", name: "Claude v2.0" },
  { id: "anthropic/claude-2.0:beta", name: "Claude v2.0 (self-moderated)" },
  { id: "anthropic/claude-2.1", name: "Claude v2.1" },
  { id: "anthropic/claude-2.1:beta", name: "Claude v2.1 (self-moderated)" },
  {
    id: "alfredpros/codellama-7b-instruct-solidity",
    name: "CodeLLaMa 7B Instruct Solidity",
  },
  { id: "arcee-ai/coder-large", name: "Coder Large" },
  { id: "mistralai/codestral-2501", name: "Codestral 2501" },
  { id: "openai/codex-mini", name: "Codex Mini" },
  { id: "cohere/command", name: "Command" },
  { id: "cohere/command-a", name: "Command A" },
  { id: "cohere/command-r", name: "Command R" },
  { id: "cohere/command-r-03-2024", name: "Command R (03-2024)" },
  { id: "cohere/command-r-08-2024", name: "Command R (08-2024)" },
  { id: "cohere/command-r-plus", name: "Command R+" },
  { id: "cohere/command-r-plus-04-2024", name: "Command R+ (04-2024)" },
  { id: "cohere/command-r-plus-08-2024", name: "Command R+ (08-2024)" },
  { id: "cohere/command-r7b-12-2024", name: "Command R7B (12-2024)" },
  {
    id: "agentica-org/deepcoder-14b-preview:free",
    name: "Deepcoder 14B Preview (free)",
  },
  {
    id: "nousresearch/deephermes-3-llama-3-8b-preview:free",
    name: "DeepHermes 3 Llama 3 8B Preview (free)",
  },
  {
    id: "nousresearch/deephermes-3-mistral-24b-preview:free",
    name: "DeepHermes 3 Mistral 24B Preview (free)",
  },
  { id: "deepseek/deepseek-prover-v2", name: "DeepSeek Prover V2" },
  { id: "deepseek/deepseek-prover-v2:free", name: "DeepSeek Prover V2 (free)" },
  {
    id: "deepseek/deepseek-r1-0528-qwen3-8b",
    name: "Deepseek R1 0528 Qwen3 8B",
  },
  {
    id: "deepseek/deepseek-r1-0528-qwen3-8b:free",
    name: "Deepseek R1 0528 Qwen3 8B (free)",
  },
  { id: "deepseek/deepseek-r1-zero:free", name: "DeepSeek R1 Zero (free)" },
  {
    id: "tngtech/deepseek-r1t-chimera:free",
    name: "DeepSeek R1T Chimera (free)",
  },
  { id: "deepseek/deepseek-chat", name: "DeepSeek V3" },
  { id: "deepseek/deepseek-chat:free", name: "DeepSeek V3 (free)" },
  { id: "deepseek/deepseek-chat-v3-0324", name: "DeepSeek V3 0324" },
  {
    id: "deepseek/deepseek-chat-v3-0324:free",
    name: "DeepSeek V3 0324 (free)",
  },
  { id: "deepseek/deepseek-v3-base:free", name: "DeepSeek V3 Base (free)" },
  { id: "mistralai/devstral-small", name: "Devstral Small" },
  { id: "mistralai/devstral-small:free", name: "Devstral Small (free)" },
  {
    id: "sentientagi/dobby-mini-unhinged-plus-llama-3.1-8b",
    name: "Dobby Mini Plus Llama 3.1 8B",
  },
  {
    id: "cognitivecomputations/dolphin-mixtral-8x22b",
    name: "Dolphin 2.9.2 Mixtral 8x22B 🐬",
  },
  {
    id: "cognitivecomputations/dolphin3.0-mistral-24b:free",
    name: "Dolphin3.0 Mistral 24B (free)",
  },
  {
    id: "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
    name: "Dolphin3.0 R1 Mistral 24B (free)",
  },
  { id: "eva-unit-01/eva-llama-3.33-70b", name: "EVA Llama 3.33 70B" },
  { id: "eva-unit-01/eva-qwen-2.5-32b", name: "EVA Qwen2.5 32B" },
  { id: "eva-unit-01/eva-qwen-2.5-72b", name: "EVA Qwen2.5 72B" },
  { id: "sao10k/fimbulvetr-11b-v2", name: "Fimbulvetr 11B v2" },
  { id: "rekaai/reka-flash-3:free", name: "Flash 3 (free)" },
  { id: "google/gemini-flash-1.5", name: "Gemini 1.5 Flash" },
  { id: "google/gemini-flash-1.5-8b", name: "Gemini 1.5 Flash 8B" },
  { id: "google/gemini-pro-1.5", name: "Gemini 1.5 Pro" },
  { id: "google/gemini-2.0-flash-001", name: "Gemini 2.0 Flash" },
  {
    id: "google/gemini-2.0-flash-exp:free",
    name: "Gemini 2.0 Flash Experimental (free)",
  },
  { id: "google/gemini-2.0-flash-lite-001", name: "Gemini 2.0 Flash Lite" },
  {
    id: "google/gemini-2.5-flash-preview",
    name: "Gemini 2.5 Flash Preview 04-17",
  },
  {
    id: "google/gemini-2.5-flash-preview:thinking",
    name: "Gemini 2.5 Flash Preview 04-17 (thinking)",
  },
  {
    id: "google/gemini-2.5-flash-preview-05-20",
    name: "Gemini 2.5 Flash Preview 05-20",
  },
  {
    id: "google/gemini-2.5-flash-preview-05-20:thinking",
    name: "Gemini 2.5 Flash Preview 05-20 (thinking)",
  },
  {
    id: "google/gemini-2.5-pro-exp-03-25",
    name: "Gemini 2.5 Pro Experimental",
  },
  {
    id: "google/gemini-2.5-pro-preview-05-06",
    name: "Gemini 2.5 Pro Preview 05-06",
  },
  { id: "google/gemini-2.5-pro-preview", name: "Gemini 2.5 Pro Preview 06-05" },
  { id: "google/gemma-2b-it", name: "Gemma 1 2B" },
  { id: "google/gemma-2-27b-it", name: "Gemma 2 27B" },
  { id: "google/gemma-2-9b-it", name: "Gemma 2 9B" },
  { id: "google/gemma-2-9b-it:free", name: "Gemma 2 9B (free)" },
  { id: "google/gemma-3-12b-it", name: "Gemma 3 12B" },
  { id: "google/gemma-3-12b-it:free", name: "Gemma 3 12B (free)" },
  { id: "google/gemma-3-1b-it:free", name: "Gemma 3 1B (free)" },
  { id: "google/gemma-3-27b-it", name: "Gemma 3 27B" },
  { id: "google/gemma-3-27b-it:free", name: "Gemma 3 27B (free)" },
  { id: "google/gemma-3-4b-it", name: "Gemma 3 4B" },
  { id: "google/gemma-3-4b-it:free", name: "Gemma 3 4B (free)" },
  { id: "google/gemma-3n-e4b-it:free", name: "Gemma 3n 4B (free)" },
  { id: "thudm/glm-4-32b", name: "GLM 4 32B" },
  { id: "thudm/glm-4-32b:free", name: "GLM 4 32B (free)" },
  { id: "thudm/glm-z1-32b", name: "GLM Z1 32B" },
  { id: "thudm/glm-z1-32b:free", name: "GLM Z1 32B (free)" },
  { id: "thudm/glm-z1-rumination-32b", name: "GLM Z1 Rumination 32B" },
  { id: "alpindale/goliath-120b", name: "Goliath 120B" },
  { id: "openai/gpt-3.5-turbo", name: "GPT-3.5 Turbo" },
  { id: "openai/gpt-3.5-turbo-0613", name: "GPT-3.5 Turbo (older v0613)" },
  { id: "openai/gpt-3.5-turbo-16k", name: "GPT-3.5 Turbo 16k" },
  { id: "openai/gpt-3.5-turbo-0125", name: "GPT-3.5 Turbo 16k" },
  { id: "openai/gpt-3.5-turbo-1106", name: "GPT-3.5 Turbo 16k (older v1106)" },
  { id: "openai/gpt-3.5-turbo-instruct", name: "GPT-3.5 Turbo Instruct" },
  { id: "openai/gpt-4", name: "GPT-4" },
  { id: "openai/gpt-4-0314", name: "GPT-4 (older v0314)" },
  { id: "openai/gpt-4-turbo", name: "GPT-4 Turbo" },
  { id: "openai/gpt-4-1106-preview", name: "GPT-4 Turbo (older v1106)" },
  { id: "openai/gpt-4-turbo-preview", name: "GPT-4 Turbo Preview" },
  { id: "openai/gpt-4.1", name: "GPT-4.1" },
  { id: "openai/gpt-4.1-mini", name: "GPT-4.1 Mini" },
  { id: "openai/gpt-4.1-nano", name: "GPT-4.1 Nano" },
  { id: "openai/gpt-4.5-preview", name: "GPT-4.5 (Preview)" },
  { id: "openai/gpt-4o", name: "GPT-4o" },
  { id: "openai/gpt-4o-2024-05-13", name: "GPT-4o (2024-05-13)" },
  { id: "openai/gpt-4o-2024-08-06", name: "GPT-4o (2024-08-06)" },
  { id: "openai/gpt-4o-2024-11-20", name: "GPT-4o (2024-11-20)" },
  { id: "openai/gpt-4o:extended", name: "GPT-4o (extended)" },
  { id: "openai/gpt-4o-search-preview", name: "GPT-4o Search Preview" },
  { id: "openai/gpt-4o-mini", name: "GPT-4o-mini" },
  { id: "openai/gpt-4o-mini-2024-07-18", name: "GPT-4o-mini (2024-07-18)" },
  {
    id: "openai/gpt-4o-mini-search-preview",
    name: "GPT-4o-mini Search Preview",
  },
  { id: "x-ai/grok-2-1212", name: "Grok 2 1212" },
  { id: "x-ai/grok-2-vision-1212", name: "Grok 2 Vision 1212" },
  { id: "x-ai/grok-3-beta", name: "Grok 3 Beta" },
  { id: "x-ai/grok-3-mini-beta", name: "Grok 3 Mini Beta" },
  { id: "x-ai/grok-beta", name: "Grok Beta" },
  { id: "x-ai/grok-vision-beta", name: "Grok Vision Beta" },
  {
    id: "nousresearch/nous-hermes-2-mixtral-8x7b-dpo",
    name: "Hermes 2 Mixtral 8x7B DPO",
  },
  {
    id: "nousresearch/hermes-2-pro-llama-3-8b",
    name: "Hermes 2 Pro - Llama-3 8B",
  },
  {
    id: "nousresearch/hermes-3-llama-3.1-405b",
    name: "Hermes 3 405B Instruct",
  },
  { id: "nousresearch/hermes-3-llama-3.1-70b", name: "Hermes 3 70B Instruct" },
  { id: "inflection/inflection-3-pi", name: "Inflection 3 Pi" },
  {
    id: "inflection/inflection-3-productivity",
    name: "Inflection 3 Productivity",
  },
  { id: "opengvlab/internvl3-14b:free", name: "InternVL3 14B (free)" },
  { id: "opengvlab/internvl3-2b:free", name: "InternVL3 2B (free)" },
  { id: "ai21/jamba-1.6-large", name: "Jamba 1.6 Large" },
  { id: "ai21/jamba-1.6-mini", name: "Jamba Mini 1.6" },
  {
    id: "moonshotai/kimi-vl-a3b-thinking:free",
    name: "Kimi VL A3B Thinking (free)",
  },
  { id: "liquid/lfm-3b", name: "LFM 3B" },
  { id: "liquid/lfm-40b", name: "LFM 40B MoE" },
  { id: "liquid/lfm-7b", name: "LFM 7B" },
  { id: "meta-llama/llama-2-70b-chat", name: "Llama 2 70B Chat" },
  { id: "meta-llama/llama-3-70b-instruct", name: "Llama 3 70B Instruct" },
  { id: "meta-llama/llama-3-8b-instruct", name: "Llama 3 8B Instruct" },
  { id: "sao10k/l3-lunaris-8b", name: "Llama 3 8B Lunaris" },
  { id: "sao10k/l3-euryale-70b", name: "Llama 3 Euryale 70B v2.1" },
  { id: "neversleep/llama-3-lumimaid-70b", name: "Llama 3 Lumimaid 70B" },
  { id: "neversleep/llama-3-lumimaid-8b", name: "Llama 3 Lumimaid 8B" },
  { id: "meta-llama/llama-3.1-405b", name: "Llama 3.1 405B (base)" },
  {
    id: "meta-llama/llama-3.1-405b:free",
    name: "Llama 3.1 405B (base) (free)",
  },
  { id: "meta-llama/llama-3.1-405b-instruct", name: "Llama 3.1 405B Instruct" },
  { id: "meta-llama/llama-3.1-70b-instruct", name: "Llama 3.1 70B Instruct" },
  { id: "meta-llama/llama-3.1-8b-instruct", name: "Llama 3.1 8B Instruct" },
  {
    id: "meta-llama/llama-3.1-8b-instruct:free",
    name: "Llama 3.1 8B Instruct (free)",
  },
  { id: "sao10k/l3.1-euryale-70b", name: "Llama 3.1 Euryale 70B v2.2" },
  {
    id: "nvidia/llama-3.1-nemotron-70b-instruct",
    name: "Llama 3.1 Nemotron 70B Instruct",
  },
  {
    id: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    name: "Llama 3.1 Nemotron Ultra 253B v1",
  },
  {
    id: "nvidia/llama-3.1-nemotron-ultra-253b-v1:free",
    name: "Llama 3.1 Nemotron Ultra 253B v1 (free)",
  },
  {
    id: "perplexity/llama-3.1-sonar-large-128k-online",
    name: "Llama 3.1 Sonar 70B Online",
  },
  {
    id: "perplexity/llama-3.1-sonar-small-128k-online",
    name: "Llama 3.1 Sonar 8B Online",
  },
  {
    id: "meta-llama/llama-3.2-11b-vision-instruct",
    name: "Llama 3.2 11B Vision Instruct",
  },
  {
    id: "meta-llama/llama-3.2-11b-vision-instruct:free",
    name: "Llama 3.2 11B Vision Instruct (free)",
  },
  { id: "meta-llama/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct" },
  {
    id: "meta-llama/llama-3.2-1b-instruct:free",
    name: "Llama 3.2 1B Instruct (free)",
  },
  { id: "meta-llama/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct" },
  {
    id: "meta-llama/llama-3.2-3b-instruct:free",
    name: "Llama 3.2 3B Instruct (free)",
  },
  {
    id: "meta-llama/llama-3.2-90b-vision-instruct",
    name: "Llama 3.2 90B Vision Instruct",
  },
  { id: "meta-llama/llama-3.3-70b-instruct", name: "Llama 3.3 70B Instruct" },
  {
    id: "meta-llama/llama-3.3-70b-instruct:free",
    name: "Llama 3.3 70B Instruct (free)",
  },
  {
    id: "meta-llama/llama-3.3-8b-instruct:free",
    name: "Llama 3.3 8B Instruct (free)",
  },
  { id: "sao10k/l3.3-euryale-70b", name: "Llama 3.3 Euryale 70B" },
  {
    id: "nvidia/llama-3.3-nemotron-super-49b-v1",
    name: "Llama 3.3 Nemotron Super 49B v1",
  },
  {
    id: "nvidia/llama-3.3-nemotron-super-49b-v1:free",
    name: "Llama 3.3 Nemotron Super 49B v1 (free)",
  },
  { id: "meta-llama/llama-4-maverick", name: "Llama 4 Maverick" },
  { id: "meta-llama/llama-4-maverick:free", name: "Llama 4 Maverick (free)" },
  { id: "meta-llama/llama-4-scout", name: "Llama 4 Scout" },
  { id: "meta-llama/llama-4-scout:free", name: "Llama 4 Scout (free)" },
  { id: "meta-llama/llama-guard-3-8b", name: "Llama Guard 3 8B" },
  { id: "meta-llama/llama-guard-4-12b", name: "Llama Guard 4 12B" },
  { id: "meta-llama/llama-guard-2-8b", name: "LlamaGuard 2 8B" },
  { id: "eleutherai/llemma_7b", name: "Llemma 7b" },
  { id: "neversleep/llama-3.1-lumimaid-70b", name: "Lumimaid v0.2 70B" },
  { id: "neversleep/llama-3.1-lumimaid-8b", name: "Lumimaid v0.2 8B" },
  { id: "arcee-ai/maestro-reasoning", name: "Maestro Reasoning" },
  { id: "alpindale/magnum-72b", name: "Magnum 72B" },
  { id: "anthracite-org/magnum-v2-72b", name: "Magnum v2 72B" },
  { id: "anthracite-org/magnum-v4-72b", name: "Magnum v4 72B" },
  { id: "microsoft/mai-ds-r1:free", name: "MAI DS R1 (free)" },
  {
    id: "inception/mercury-coder-small-beta",
    name: "Mercury Coder Small Beta",
  },
  { id: "sophosympatheia/midnight-rose-70b", name: "Midnight Rose 70B" },
  { id: "minimax/minimax-01", name: "MiniMax-01" },
  { id: "mistralai/ministral-3b", name: "Ministral 3B" },
  { id: "mistralai/ministral-8b", name: "Ministral 8B" },
  { id: "mistralai/mistral-7b-instruct", name: "Mistral 7B Instruct" },
  {
    id: "mistralai/mistral-7b-instruct:free",
    name: "Mistral 7B Instruct (free)",
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.1",
    name: "Mistral 7B Instruct v0.1",
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.2",
    name: "Mistral 7B Instruct v0.2",
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.3",
    name: "Mistral 7B Instruct v0.3",
  },
  { id: "mistralai/mistral-large", name: "Mistral Large" },
  { id: "mistralai/mistral-large-2407", name: "Mistral Large 2407" },
  { id: "mistralai/mistral-large-2411", name: "Mistral Large 2411" },
  { id: "mistralai/mistral-medium", name: "Mistral Medium" },
  { id: "mistralai/mistral-medium-3", name: "Mistral Medium 3" },
  { id: "mistralai/mistral-nemo", name: "Mistral Nemo" },
  { id: "mistralai/mistral-nemo:free", name: "Mistral Nemo (free)" },
  { id: "nothingiisreal/mn-celeste-12b", name: "Mistral Nemo 12B Celeste" },
  { id: "infermatic/mn-inferor-12b", name: "Mistral Nemo Inferor 12B" },
  { id: "mistralai/mistral-small", name: "Mistral Small" },
  { id: "mistralai/mistral-small-24b-instruct-2501", name: "Mistral Small 3" },
  {
    id: "mistralai/mistral-small-24b-instruct-2501:free",
    name: "Mistral Small 3 (free)",
  },
  {
    id: "mistralai/mistral-small-3.1-24b-instruct",
    name: "Mistral Small 3.1 24B",
  },
  {
    id: "mistralai/mistral-small-3.1-24b-instruct:free",
    name: "Mistral Small 3.1 24B (free)",
  },
  { id: "mistralai/mistral-tiny", name: "Mistral Tiny" },
  { id: "mistralai/mixtral-8x22b-instruct", name: "Mixtral 8x22B Instruct" },
  { id: "mistralai/mixtral-8x7b-instruct", name: "Mixtral 8x7B Instruct" },
  {
    id: "moonshotai/moonlight-16b-a3b-instruct:free",
    name: "Moonlight 16B A3B Instruct (free)",
  },
  { id: "pygmalionai/mythalion-13b", name: "Mythalion 13B" },
  { id: "gryphe/mythomax-l2-13b", name: "MythoMax 13B" },
  { id: "neversleep/noromaid-20b", name: "Noromaid 20B" },
  { id: "amazon/nova-lite-v1", name: "Nova Lite 1.0" },
  { id: "amazon/nova-micro-v1", name: "Nova Micro 1.0" },
  { id: "amazon/nova-pro-v1", name: "Nova Pro 1.0" },
  { id: "openai/o1", name: "o1" },
  { id: "openai/o1-mini", name: "o1-mini" },
  { id: "openai/o1-mini-2024-09-12", name: "o1-mini (2024-09-12)" },
  { id: "openai/o1-preview", name: "o1-preview" },
  { id: "openai/o1-preview-2024-09-12", name: "o1-preview (2024-09-12)" },
  { id: "openai/o1-pro", name: "o1-pro" },
  { id: "openai/o3", name: "o3" },
  { id: "openai/o3-mini", name: "o3 Mini" },
  { id: "openai/o3-mini-high", name: "o3 Mini High" },
  { id: "openai/o4-mini", name: "o4 Mini" },
  { id: "openai/o4-mini-high", name: "o4 Mini High" },
  { id: "open-r1/olympiccoder-32b:free", name: "OlympicCoder 32B (free)" },
  { id: "all-hands/openhands-lm-32b-v0.1", name: "OpenHands LM 32B V0.1" },
  { id: "microsoft/phi-4", name: "Phi 4" },
  {
    id: "microsoft/phi-4-multimodal-instruct",
    name: "Phi 4 Multimodal Instruct",
  },
  { id: "microsoft/phi-4-reasoning:free", name: "Phi 4 Reasoning (free)" },
  { id: "microsoft/phi-4-reasoning-plus", name: "Phi 4 Reasoning Plus" },
  {
    id: "microsoft/phi-4-reasoning-plus:free",
    name: "Phi 4 Reasoning Plus (free)",
  },
  {
    id: "microsoft/phi-3-medium-128k-instruct",
    name: "Phi-3 Medium 128K Instruct",
  },
  {
    id: "microsoft/phi-3-mini-128k-instruct",
    name: "Phi-3 Mini 128K Instruct",
  },
  {
    id: "microsoft/phi-3.5-mini-128k-instruct",
    name: "Phi-3.5 Mini 128K Instruct",
  },
  { id: "mistralai/pixtral-12b", name: "Pixtral 12B" },
  { id: "mistralai/pixtral-large-2411", name: "Pixtral Large 2411" },
  { id: "qwen/qwen-2-72b-instruct", name: "Qwen 2 72B Instruct" },
  { id: "qwen/qwen-vl-max", name: "Qwen VL Max" },
  { id: "qwen/qwen-vl-plus", name: "Qwen VL Plus" },
  { id: "qwen/qwen-max", name: "Qwen-Max" },
  { id: "qwen/qwen-plus", name: "Qwen-Plus" },
  { id: "qwen/qwen-turbo", name: "Qwen-Turbo" },
  { id: "qwen/qwen-2.5-72b-instruct", name: "Qwen2.5 72B Instruct" },
  {
    id: "qwen/qwen-2.5-72b-instruct:free",
    name: "Qwen2.5 72B Instruct (free)",
  },
  { id: "qwen/qwen-2.5-7b-instruct", name: "Qwen2.5 7B Instruct" },
  { id: "qwen/qwen-2.5-7b-instruct:free", name: "Qwen2.5 7B Instruct (free)" },
  {
    id: "qwen/qwen-2.5-coder-32b-instruct",
    name: "Qwen2.5 Coder 32B Instruct",
  },
  {
    id: "qwen/qwen-2.5-coder-32b-instruct:free",
    name: "Qwen2.5 Coder 32B Instruct (free)",
  },
  { id: "qwen/qwen2.5-vl-32b-instruct", name: "Qwen2.5 VL 32B Instruct" },
  {
    id: "qwen/qwen2.5-vl-32b-instruct:free",
    name: "Qwen2.5 VL 32B Instruct (free)",
  },
  {
    id: "qwen/qwen2.5-vl-3b-instruct:free",
    name: "Qwen2.5 VL 3B Instruct (free)",
  },
  { id: "qwen/qwen2.5-vl-72b-instruct", name: "Qwen2.5 VL 72B Instruct" },
  {
    id: "qwen/qwen2.5-vl-72b-instruct:free",
    name: "Qwen2.5 VL 72B Instruct (free)",
  },
  { id: "qwen/qwen-2.5-vl-7b-instruct", name: "Qwen2.5-VL 7B Instruct" },
  {
    id: "qwen/qwen-2.5-vl-7b-instruct:free",
    name: "Qwen2.5-VL 7B Instruct (free)",
  },
  { id: "qwen/qwen3-14b", name: "Qwen3 14B" },
  { id: "qwen/qwen3-14b:free", name: "Qwen3 14B (free)" },
  { id: "qwen/qwen3-235b-a22b", name: "Qwen3 235B A22B" },
  { id: "qwen/qwen3-235b-a22b:free", name: "Qwen3 235B A22B (free)" },
  { id: "qwen/qwen3-30b-a3b", name: "Qwen3 30B A3B" },
  { id: "qwen/qwen3-30b-a3b:free", name: "Qwen3 30B A3B (free)" },
  { id: "qwen/qwen3-32b", name: "Qwen3 32B" },
  { id: "qwen/qwen3-32b:free", name: "Qwen3 32B (free)" },
  { id: "qwen/qwen3-8b", name: "Qwen3 8B" },
  { id: "qwen/qwen3-8b:free", name: "Qwen3 8B (free)" },
  { id: "featherless/qwerky-72b:free", name: "Qwerky 72B (free)" },
  { id: "qwen/qwq-32b", name: "QwQ 32B" },
  { id: "qwen/qwq-32b:free", name: "QwQ 32B (free)" },
  { id: "qwen/qwq-32b-preview", name: "QwQ 32B Preview" },
  { id: "arliai/qwq-32b-arliai-rpr-v1:free", name: "QwQ 32B RpR v1 (free)" },
  { id: "deepseek/deepseek-r1", name: "R1" },
  { id: "deepseek/deepseek-r1:free", name: "R1 (free)" },
  { id: "deepseek/deepseek-r1-0528", name: "R1 0528" },
  { id: "deepseek/deepseek-r1-0528:free", name: "R1 0528 (free)" },
  { id: "perplexity/r1-1776", name: "R1 1776" },
  {
    id: "deepseek/deepseek-r1-distill-llama-70b",
    name: "R1 Distill Llama 70B",
  },
  {
    id: "deepseek/deepseek-r1-distill-llama-70b:free",
    name: "R1 Distill Llama 70B (free)",
  },
  { id: "deepseek/deepseek-r1-distill-llama-8b", name: "R1 Distill Llama 8B" },
  {
    id: "deepseek/deepseek-r1-distill-qwen-1.5b",
    name: "R1 Distill Qwen 1.5B",
  },
  { id: "deepseek/deepseek-r1-distill-qwen-14b", name: "R1 Distill Qwen 14B" },
  {
    id: "deepseek/deepseek-r1-distill-qwen-14b:free",
    name: "R1 Distill Qwen 14B (free)",
  },
  { id: "deepseek/deepseek-r1-distill-qwen-32b", name: "R1 Distill Qwen 32B" },
  {
    id: "deepseek/deepseek-r1-distill-qwen-32b:free",
    name: "R1 Distill Qwen 32B (free)",
  },
  { id: "deepseek/deepseek-r1-distill-qwen-7b", name: "R1 Distill Qwen 7B" },
  { id: "undi95/remm-slerp-l2-13b", name: "ReMM SLERP 13B" },
  { id: "thedrummer/rocinante-12b", name: "Rocinante 12B" },
  { id: "mistralai/mistral-saba", name: "Saba" },
  { id: "sarvamai/sarvam-m", name: "Sarvam-M" },
  { id: "sarvamai/sarvam-m:free", name: "Sarvam-M (free)" },
  {
    id: "shisa-ai/shisa-v2-llama3.3-70b:free",
    name: "Shisa V2 Llama 3.3 70B  (free)",
  },
  { id: "thedrummer/skyfall-36b-v2", name: "Skyfall 36B V2" },
  { id: "perplexity/sonar", name: "Sonar" },
  { id: "perplexity/sonar-deep-research", name: "Sonar Deep Research" },
  { id: "perplexity/sonar-pro", name: "Sonar Pro" },
  { id: "perplexity/sonar-reasoning", name: "Sonar Reasoning" },
  { id: "perplexity/sonar-reasoning-pro", name: "Sonar Reasoning Pro" },
  { id: "raifle/sorcererlm-8x22b", name: "SorcererLM 8x22B" },
  { id: "arcee-ai/spotlight", name: "Spotlight" },
  { id: "aetherwiing/mn-starcannon-12b", name: "Starcannon 12B" },
  { id: "undi95/toppy-m-7b", name: "Toppy M 7B" },
  {
    id: "scb10x/llama3.1-typhoon2-70b-instruct",
    name: "Typhoon2 70B Instruct",
  },
  { id: "thedrummer/unslopnemo-12b", name: "UnslopNemo 12B" },
  { id: "thedrummer/valkyrie-49b-v1", name: "Valkyrie 49B V1" },
  { id: "arcee-ai/virtuoso-large", name: "Virtuoso Large" },
  { id: "arcee-ai/virtuoso-medium-v2", name: "Virtuoso Medium V2" },
  { id: "mancer/weaver", name: "Weaver (alpha)" },
  { id: "microsoft/wizardlm-2-8x22b", name: "WizardLM-2 8x22B" },
  { id: "01-ai/yi-large", name: "Yi Large" },
];

export const defaultModel = "google/gemini-2.5-pro-preview";
